model: dino_detrex
architecture: dino/configs/dino-swin/dino_swin_large_384_5scale_36ep.py
checkpoint_path: 'https://huggingface.co/CanopyRS/dino-swin-l-384-multi-NQOS/resolve/main/model_best.pth'
augmentation_brightness: 0.2
augmentation_brightness_prob: 0.5
augmentation_contrast: 0.2
augmentation_contrast_prob: 0.5
augmentation_crop_fallback_to_augmentation_image_size: false
augmentation_crop_min_intersection_ratio: 0.5
augmentation_crop_prob: 0.5
augmentation_early_conditional_image_size: 2000
augmentation_flip_horizontal: true
augmentation_flip_vertical: true
augmentation_hue: 10
augmentation_hue_prob: 0.3
augmentation_image_size:
- 1024
- 1777
augmentation_rotation: 30.0
augmentation_rotation_prob: 0.5
augmentation_saturation: 0.2
augmentation_saturation_prob: 0.5
augmentation_train_crop_size_range:
- 666
- 2666
backbone_model_pretrained: true
batch_size: 1
box_predictions_per_image: 500
data_root_path: 'TODO: change this for training!'
dataloader_num_workers: 4
eval_epoch_interval: 2
lr: 0.0001
main_metric: bbox/AP
max_epochs: 80
num_classes: 1
scheduler_epochs_steps:
- 64
- 72
scheduler_gamma: 0.1
scheduler_type: WarmupMultiStepLR
scheduler_warmup_steps: 5000
seed: 1
test_dataset_names: []
train_dataset_names:
- brazil_zf2
- ecuador_tiputini
- panama_aguasalud
- quebec_trees
- unitedstates_neon
- global_oamtcd
train_log_interval: 10
train_output_path: 'TODO: change this for training!'
use_amp: true
use_gradient_checkpointing: true
valid_dataset_names:
- brazil_zf2
- ecuador_tiputini
- panama_aguasalud
- quebec_trees
- unitedstates_neon
- global_oamtcd
wandb_project: 'TODO: change this for training!'
