components_configs:
  - tilerizer:
      tile_type: tile
      tile_size: 1777
      tile_overlap: 0.75
      ground_resolution: 0.045
  - detector: default_components/detector_deepforest
  - segmenter: default_components/segmenter_sam2
  - aggregator: default_components/aggregator_sam2