model: dino_detrex
architecture: dino/configs/dino-swin/dino_swin_large_384_5scale_36ep.py
checkpoint_path: https://huggingface.co/CanopyRS/dino-swin-l-384-multi-NQOS-selvamask-FT/resolve/main/model_best.pth
augmentation_brightness: 0.2
augmentation_brightness_prob: 0.5
augmentation_contrast: 0.2
augmentation_contrast_prob: 0.5
augmentation_crop_fallback_to_augmentation_image_size: false
augmentation_crop_min_intersection_ratio: 0.5
augmentation_crop_prob: 1.0
augmentation_early_conditional_image_size: 2000
augmentation_flip_horizontal: true
augmentation_flip_vertical: true
augmentation_hue: 10
augmentation_hue_prob: 0.3
augmentation_image_size:
- 1024
- 1777
augmentation_rotation: 30.0
augmentation_rotation_prob: 0.5
augmentation_saturation: 0.2
augmentation_saturation_prob: 0.5
augmentation_train_crop_size_range:
- 666
- 2666
backbone_model_pretrained: true
batch_size: 1
box_predictions_per_image: 500
data_root_path: 'TODO: change this for training!'
dataloader_num_workers: 4
eval_epoch_interval: 3
freeze_layers: 2
grad_accumulation_steps: 1
lr: 5.0e-05
main_metric: bbox/AP
max_epochs: 800
num_classes: 1
scheduler_epochs_steps:
- 640
- 720
scheduler_gamma: 0.1
scheduler_type: WarmupCosineLR
scheduler_warmup_steps: 100
seed: 33
test_dataset_names: []
train_dataset_names:
- extracted_segm_pp/selvamask
train_log_interval: 10
train_output_path: 'TODO: change this for training!'
use_amp: true
use_gradient_checkpointing: true
valid_dataset_names:
- extracted_segm_pp/selvamask
wandb_project: 'TODO: change this for training!'