components_configs:
  - tilerizer:
      tile_type: tile
      tile_size: 800
      tile_overlap: 0.75
      ground_resolution: 0.1
  - detector: detectors/fasterrcnn_r50_single_S
  - aggregator:
      nms_algorithm: 'iou'
      score_threshold: 0.4
      nms_threshold: 0.2
      edge_band_buffer_percentage: 0.05
      scores_weights: { 'detector_score': 1.0 }
