components_configs:
  - tilerizer:
      tile_type: tile
      tile_size: 1777
      tile_overlap: 0.75
      ground_resolution: 0.045
  - detector: detectors/dino_swinL_multi_NQOS_selvamask_FT.yaml
  - aggregator:
      nms_algorithm: 'iou'
      score_threshold: 0.4
      nms_threshold: 0.7
      edge_band_buffer_percentage: 0.05
      scores_weights: { 'detector_score': 1.0 }
  - segmenter: segmenters/sam3_multi_selvamask_FT.yaml
  - aggregator:
      nms_algorithm: 'ioa-disambiguate'
      score_threshold: 0.6
      nms_threshold: 0.05
      edge_band_buffer_percentage: 0.05
      scores_weights: {'detector_score': 0.5, 'segmenter_score': 0.5}
      scores_weighting_method: 'weighted_geometric_mean'